# This is a basic workflow to help you get started with Actions

name: Cypress testing on workflow.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # - name: run pr test cases
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm run start:ci
      #     env: grepTags=@smoke
      - name: Install and verify cypress
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Run cypress test
        run: npx cypress run
        with:
          env: tags='pr'
        continue-on-error: false
